sudo: required
dist: trusty

language: php
php:
   - '7.0'

addons:
   chrome: stable

install:
   - cp .env.dusk .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://beta-sm.45.in &
   - php artisan serve &

script:
   - php artisan dusk tests/Browser/LoginTest.php

notification:
   - email: false
