sudo: required
dist: trusty

addons:
   chrome: stable

install:
   - sudo apt-get install -y language-pack-en-base
   - sudo LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
   - sudo apt-get update
   - sudo apt-get install php7.0
   - php -v
   - cp .env.dusk .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve &

script:
   - php artisan dusk
