sudo: required
dist: trusty

language: php
php:
   - '7.0'

addons:
   chrome: stable

install:
   - cp .env.dusk .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - php artisan serve &

script:
   - php artisan dusk tests/Browser/LoginTest.php

notifications:
   email: false
