sudo: required
dist: trusty

addons:
   chrome: stable

install:
   - apt-get install php7.0 &
   - cp .env.dusk .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve &
   - php -v

script:
   - php artisan dusk
